// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUlvFuOdPFeuFAtHvmp132Dtf9FDJ-uQ8',
    appId: '1:482601678376:web:5309dd718d1799937c271d',
    messagingSenderId: '482601678376',
    projectId: 'darleycomma',
    authDomain: 'darleycomma.firebaseapp.com',
    storageBucket: 'darleycomma.appspot.com',
    measurementId: 'G-REWJKFBHYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3DS4w1tdKUKlDaya86rwqhwbb7cDPcA',
    appId: '1:482601678376:android:fdd4ad64ec1e5ce37c271d',
    messagingSenderId: '482601678376',
    projectId: 'darleycomma',
    storageBucket: 'darleycomma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHR8pe9qY7cYMBG0Ah_5cGAbEBO1LQdA',
    appId: '1:482601678376:ios:24603a6fac440ef27c271d',
    messagingSenderId: '482601678376',
    projectId: 'darleycomma',
    storageBucket: 'darleycomma.appspot.com',
    iosClientId: '482601678376-crn890r761jsu78dp8gc4ktitot7hbes.apps.googleusercontent.com',
    iosBundleId: 'com.comma.darleyexpress',
  );
}
