import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_JOR': {
          "darley": "دارلي إكسبريس",
          "signUp": "التسجيل",
          "signIn": "تسجيل الدخول",
          "welcomeBack": "مرحبًا مرة أخرى، لقد افتقدناك",
          "fill": "املأ معلوماتك أدناه أو سجل باستخدام حسابك الاجتماعي",
          "pleaseEmail": "الرجاء إدخال بريد إلكتروني صالح",
          "email": "البريد الإلكتروني",
          "pleasePassword": "الرجاء إدخال كلمة مرور تتكون على الأقل من 8 أحرف",
          "password": "كلمة المرور",
          "forgot": "نسيت كلمة المرور؟",
          "dontHave": "ليس لديك حساب؟",
          "or": "أو",
          "haveAcc": "هل لديك حساب بالفعل؟",
          "name": "الاسم",
          "skip": "تخطى",
          "pleaseName": "الرجاء إدخال اسمك",
          "agree": "أوافق على",
          "term": "الشروط والأحكام",
          "invalidCredentials": "بيانات الاعتماد غير صالحة",
          "email-already-in-use": "البريد الإلكتروني مستخدم بالفعل",
          "submit": "إرسال",
          "resetPassword": "إعادة تعيين كلمة المرور",
          "passwordSent":
              "لإعادة تعيين كلمة المرور، تحقق من صندوق البريد الوارد أو البريد المزعج الخاص بك",
          "search": "بحث",
          "deliverTO": "توصيل إلى",
          "home": "الرئيسية",
          "profile": "الملف الشخصي",
          "cart": "السلة",
          "wishlist": "المفضلة",
          "category": "الفئة",
          "seeAll": "عرض الكل",
          "noProducts": "لا توجد منتجات",
          "noFavorites": "لا توجد منتجات مفضلة حتى الآن",
          "AED": "درهم إماراتي",
          "subtotal": "المجموع الفرعي",
          "items": "العناصر",
          "deliveryFee": "رسوم التوصيل",
          "pleaseFirst": "الرجاء تسجيل الدخول أولاً",
          "CHECKOUT": "الدفع",
          "emptyCart": "سلة التسوق فارغة",
          "orderPlaced": "تم وضع الطلب",
          "total": "الإجمالي",
          "pleaseAddress": "الرجاء إضافة عنوان أولاً",
          "placeOrder": "إرسال الطلب",
          "shipping": "عنوان الشحن",
          "addNew": "إضافة عنوان جديد",
          "change": "تغيير",
          "apply": "تطبيق",
          "upTo": "حتى",
          "orderList": "قائمة الطلبات",
          "expired": "انتهت صلاحية رمز الخصم",
          "noCode": "لم يتم العثور على رمز",
          "havePromo": "هل لديك رمز ترويجي؟",
          "promo": "رمز الترويج",
          "address": "العنوان",
          "newAddress": "عنوان جديد",
          "noAddress": "لا يوجد عناوين محفوظة",
          "default": "افتراضي",
          "homes": "المنزل",
          "work": "العمل",
          "label": "علامة العنوان",
          "pleaseAddressName": "الرجاء إدخال اسم العنوان",
          "pleaseYourAddress": "الرجاء إدخال عنوانك",
          "pleasephone": "الرجاء إدخال رقم هاتفك",
          "addressName": "اسم العنوان",
          "phone": "الهاتف",
          "categories": "الفئات",
          "orderNo": "رقم الطلب",
          "inProgress": "قيد التنفيذ",
          "cancel": "ملغي",
          "complete": "مكتمل",
          "inDelivery": "قيد التوصيل",
          "discount": "خصم",
          "makeDefualt": "تعيينه كافتراضي",
          "deleteAddress": "حذف العنوان",
          "orderNumber": "رقم الطلب",
          "orderT&D": "وقت وتاريخ الطلب",
          "status": "الحالة",
          "myOrders": "طلباتي",
          "manageAdd": "إدارة العناوين",
          "settings": "الإعدادات",
          "help": "مركز المساعدة",
          "contactUs": "اتصل بنا",
          "logOut": "تسجيل الخروج",
          "notifications": "الإشعارات",
          "noNotifications": "لا توجد إشعارات",
          "changeEmail": "تغيير البريد الإلكتروني",
          "changePass": "تغيير كلمة المرور",
          "changeLang": "تغيير اللغة",
          "deleteAccount": "حذف حسابك",
          "reviewSent": "تم إرسال التقييم",
          "reviewOrder": "مراجعة الطلب",
          "message": "رسالة",
          "veryGood": "جيد جدًا",
          "noPayment": "لا توجد طرق دفع محفوظة",
          "price": "السعر",
          "stock": "في المخزن",
          "titleAr": "العنوان باللغة العربية",
          "titleEn": "العنوان باللغة الإنجليزية",
          "descriptionEn": "الوصف باللغة الإنجليزية",
          "descriptionAr": "الوصف باللغة العربية",
          "discountP": "نسبة الخصم",
          "max": "الحد الأقصى للخصم",
          "code": "كود الكوبون",
          "out": "انتهت الكمية",
          "addTo": "اضف للسلة",
          "paymentMethod": "طرق الدفع"
        },
        'en_US': {
          "darley": "Darley Express",
          "signUp": "Sign Up",
          "signIn": "Sign In",
          "welcomeBack": "Welcome back, You've been missed",
          "fill":
              "Fill your information below or register with your social account",
          "pleaseEmail": "Please enter valid Email",
          "email": "Email",
          "pleasePassword": "Please enter password at least 8 characters",
          "password": "Password",
          "forgot": "Forgot password?",
          "dontHave": "Don't have an account?",
          "or": "OR",
          "haveAcc": "Already have an account?",
          "name": "Name",
          "skip": "Skip",
          "pleaseName": "Please enter your name",
          "agree": "Agree with",
          "term": "Terms & Conditions",
          "invalidCredentials": "Invalid credentials",
          "email-already-in-use": "Email already used",
          "submit": "Submit",
          "resetPassword": "Reset your password",
          "passwordSent":
              "To reset your password check your email inbox or spam",
          "search": "Search",
          "deliverTO": "Deliver to",
          "home": "Home",
          "profile": "Profile",
          "cart": "Cart",
          "wishlist": "Wishlist",
          "category": "Category",
          "seeAll": "See All",
          "noProducts": "No products found",
          "noFavorites": "No favorite products yet",
          "AED": "AED",
          "subtotal": "Subtotal",
          "items": "items",
          "deliveryFee": "Delivery Fee",
          "pleaseFirst": "Please sign in first",
          "CHECKOUT": "CHECKOUT",
          "emptyCart": "Your cart is empty",
          "orderPlaced": "Order placed",
          "total": "Total",
          "pleaseAddress": "Please add an address first",
          "placeOrder": "Place order",
          "shipping": "Shipping address",
          "addNew": "Add new address",
          "change": "Change",
          "apply": "Apply",
          "upTo": " up to",
          "orderList": "Order list",
          "expired": "Promo code expired",
          "noCode": " No code found",
          "havePromo": " Do you have promo code?",
          "promo": "Promo code",
          "address": "Address",
          "newAddress": "New Address",
          "noAddress": "No saved address",
          "default": "Default",
          "homes": "Home",
          "work": "Work",
          "label": " Address label",
          "pleaseAddressName": "Please enter address name",
          "pleaseYourAddress": "Please enter your address",
          "pleasephone": "Please enter your phone number",
          "addressName": "Address name",
          "phone": "Phone",
          "categories": "Categories",
          "orderNo": "Order No",
          "inProgress": "In progress",
          "cancel": "canceled",
          "complete": "completed",
          "inDelivery": "In delivery",
          "discount": "Discount",
          "makeDefualt": "Make it default",
          "deleteAddress": "Delete Address",
          "orderNumber": "Order Number",
          "orderT&D": "Order time & date",
          "status": "Status",
          "myOrders": "My orders",
          "manageAdd": "Manage Address",
          "settings": "Settings",
          "help": "Help Center",
          "contactUs": "Contact US",
          "logOut": "Log Out",
          "notifications": "Notifications",
          "noNotifications": "No notifications there",
          "changeEmail": "Change Email",
          "changePass": "Change Password",
          "changeLang": "Change language",
          "deleteAccount": "Delete your Account",
          "reviewSent": "Review sent",
          "reviewOrder": "Review order",
          "message": "Message",
          "veryGood": "Very good",
          "noPayment": "No saved payment methods",
          "price": "Price",
          "stock": "In stock",
          "titleAr": "Title in Arabic",
          "titleEn": "Title in English",
          "descriptionEn": "Description in English",
          "descriptionAr": "Description in Arabic",
          "discountP": "Discount percent",
          "max": "Max dicount",
          "code": "Coupon code",
          "out": "Out of stock",
          "addTo": "Add to cart",
          "paymentMethod": "Payment methods"
        }
      };
}
