name: darleyexpress
description: Ecommerce app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  firebase_dynamic_links: ^5.4.3
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.12.2
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  icons_plus: ^4.0.0

  paymob_payment: ^0.0.1+1
  flutter_stripe: ^9.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/lang/
