name: darleyexpress
description: Ecommerce app

publish_to: "none"

version: 1.0.8+13

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  share_plus: ^9.0.0
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.4
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  icons_plus: ^5.0.0
  carousel_slider: ^4.2.1
  ticket_widget: ^1.0.2
  flutter_credit_card: ^4.0.1
  cryptlib_2_0: ^0.0.3
  image_pickers: ^2.0.4+7
  file_picker: ^8.0.6
  csv: ^6.0.0
  webview_flutter: ^4.4.4
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: any
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
